{
 "title": "Dashboard principal",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Monitoring (tmp)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Suivi du nombre de données par  heure",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "WATER",
     "select": [
      [
       { "params": [ "daily_consumption" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "counter_index" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Suivi du nombre de données par heure",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "WATER",
     "select": [
      [
       { "params": [ "daily_consumption" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "counter_index" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Suivi principal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Conso journalière (en L)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "WATER",
     "query": "SELECT \"daily_consumption\" FROM \"WATER\" ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "daily_consumption" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consommation d'eau par pas de 20 min (en L)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "alias": "Consommation",
     "groupBy": [
      { "params": [ "20m" ], "type": "time" }
     ],
     "measurement": "WATER",
     "query": "SELECT difference(last(\"daily_consumption\"))FROM \"WATER\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "daily_consumption" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consommation d'eau par heure (en L)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "alias": "Consommation",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "WATER",
     "query": "SELECT difference(last(\"daily_consumption\"))FROM \"WATER\" WHERE $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "daily_consumption" ], "type": "field" },
       {
        "params": [],
        "type": "spread"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Index compteur (en m3)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "WATER",
     "query": "SELECT \"counter_index\" FROM \"WATER\" ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "counter_index" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consommation d'eau journalière (en L)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "alias": "Consommation",
     "measurement": "WATER",
     "query": "SELECT \"daily_consumption\" FROM \"WATER\"",
     "select": [
      [
       { "params": [ "daily_consumption" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}